# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"GH_HOST": "00_core.ipynb",
         "GhApi": "00_core.ipynb",
         "GhApi.delete_release": "00_core.ipynb",
         "GhApi.create_release": "00_core.ipynb",
         "GhApi.list_tags": "00_core.ipynb",
         "GhApi.list_branches": "00_core.ipynb",
         "EMPTY_TREE_SHA": "00_core.ipynb",
         "GhApi.create_branch_empty": "00_core.ipynb",
         "GhApi.delete_tag": "00_core.ipynb",
         "GhApi.delete_branch": "00_core.ipynb",
         "GhApi.get_branch": "00_core.ipynb",
         "GhApi.list_files": "00_core.ipynb",
         "GhApi.get_content": "00_core.ipynb",
         "GhApi.update_contents": "00_core.ipynb",
         "GhApi.enable_pages": "00_core.ipynb",
         "print_summary": "00_core.ipynb",
         "ghapi": "01_cli.ipynb",
         "ghpath": "01_cli.ipynb",
         "ghraw": "01_cli.ipynb",
         "completion_ghapi": "01_cli.ipynb",
         "GH_OPENAPI_URL": "90_build_lib.ipynb",
         "build_funcs": "90_build_lib.ipynb",
         "GhMeta": "90_build_lib.ipynb"}

modules = ["core.py",
           "cli.py",
           "build_lib.py"]

doc_url = "https://ghapi.fast.ai/"

git_url = "https://github.com/fastai/ghapi/tree/master/"

def custom_doc_links(name): return None
