# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"GH_HOST": "00_core.ipynb",
         "GhApi": "00_core.ipynb",
         "GH_OPENAPI_URL": "build_lib.ipynb",
         "GH_DOC_URL": "build_lib.ipynb",
         "build_funcs": "build_lib.ipynb"}

modules = ["core.py",
           "build_lib.py"]

doc_url = "https://fastai.github.io/ghapi/"

git_url = "https://github.com/fastai/ghapi/tree/master/"

def custom_doc_links(name): return None
