# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"GH_HOST": "00_core.ipynb",
         "GhApi": "00_core.ipynb",
         "GhApi.delete_release": "00_core.ipynb",
         "GhApi.create_release": "00_core.ipynb",
         "GhApi.list_tags": "00_core.ipynb",
         "GhApi.list_branches": "00_core.ipynb",
         "GhApi.enable_pages": "00_core.ipynb",
         "GH_OPENAPI_URL": "90_build_lib.ipynb",
         "build_funcs": "90_build_lib.ipynb",
         "GhMeta": "90_build_lib.ipynb"}

modules = ["core.py",
           "build_lib.py"]

doc_url = "https://ghapi.fast.ai/"

git_url = "https://github.com/fastai/ghapi/tree/master/"

def custom_doc_links(name): return None
