funcs = [('', 'get', 'repos/get', 'Get a repository', 'v3/repos/#get-a-repository', []),
 ('', 'patch', 'repos/update', 'Update a repository', 'v3/repos/#update-a-repository', ['name', 'description', 'homepage', 'private', 'visibility', 'has_issues', 'has_projects', 'has_wiki', 'is_template', 'default_branch', 'allow_squash_merge', 'allow_merge_commit', 'allow_rebase_merge', 'delete_branch_on_merge', 'archived']),
 ('', 'delete', 'repos/delete', 'Delete a repository', 'v3/repos/#delete-a-repository', []),
 ('/actions/artifacts', 'get', 'actions/list-artifacts-for-repo', 'List artifacts for a repository', 'rest/reference/actions#list-artifacts-for-a-repository', []),
 ('/actions/artifacts/{artifact_id}', 'get', 'actions/get-artifact', 'Get an artifact', 'rest/reference/actions#get-an-artifact', []),
 ('/actions/artifacts/{artifact_id}', 'delete', 'actions/delete-artifact', 'Delete an artifact', 'rest/reference/actions#delete-an-artifact', []),
 ('/actions/artifacts/{artifact_id}/{archive_format}', 'get', 'actions/download-artifact', 'Download an artifact', 'rest/reference/actions#download-an-artifact', []),
 ('/actions/jobs/{job_id}', 'get', 'actions/get-job-for-workflow-run', 'Get a job for a workflow run', 'rest/reference/actions#get-a-job-for-a-workflow-run', []),
 ('/actions/jobs/{job_id}/logs', 'get', 'actions/download-job-logs-for-workflow-run', 'Download job logs for a workflow run', 'rest/reference/actions#download-job-logs-for-a-workflow-run', []),
 ('/actions/permissions', 'get', 'actions/get-github-actions-permissions-repository', 'Get GitHub Actions permissions for a repository', 'rest/reference/actions#get-github-actions-permissions-for-a-repository', []),
 ('/actions/permissions', 'put', 'actions/set-github-actions-permissions-repository', 'Set GitHub Actions permissions for a repository', 'rest/reference/actions#set-github-actions-permissions-for-a-repository', ['enabled', 'allowed_actions']),
 ('/actions/permissions/selected-actions', 'get', 'actions/get-allowed-actions-repository', 'Get allowed actions for a repository', 'rest/reference/actions#get-allowed-actions-for-a-repository', []),
 ('/actions/permissions/selected-actions', 'put', 'actions/set-allowed-actions-repository', 'Set allowed actions for a repository', 'rest/reference/actions#set-allowed-actions-for-a-repository', []),
 ('/actions/runners', 'get', 'actions/list-self-hosted-runners-for-repo', 'List self-hosted runners for a repository', 'rest/reference/actions#list-self-hosted-runners-for-a-repository', []),
 ('/actions/runners/downloads', 'get', 'actions/list-runner-applications-for-repo', 'List runner applications for a repository', 'rest/reference/actions#list-runner-applications-for-a-repository', []),
 ('/actions/runners/registration-token', 'post', 'actions/create-registration-token-for-repo', 'Create a registration token for a repository', 'rest/reference/actions#create-a-registration-token-for-a-repository', []),
 ('/actions/runners/remove-token', 'post', 'actions/create-remove-token-for-repo', 'Create a remove token for a repository', 'rest/reference/actions#create-a-remove-token-for-a-repository', []),
 ('/actions/runners/{runner_id}', 'get', 'actions/get-self-hosted-runner-for-repo', 'Get a self-hosted runner for a repository', 'rest/reference/actions#get-a-self-hosted-runner-for-a-repository', []),
 ('/actions/runners/{runner_id}', 'delete', 'actions/delete-self-hosted-runner-from-repo', 'Delete a self-hosted runner from a repository', 'rest/reference/actions#delete-a-self-hosted-runner-from-a-repository', []),
 ('/actions/runs', 'get', 'actions/list-workflow-runs-for-repo', 'List workflow runs for a repository', 'rest/reference/actions#list-workflow-runs-for-a-repository', []),
 ('/actions/runs/{run_id}', 'get', 'actions/get-workflow-run', 'Get a workflow run', 'rest/reference/actions#get-a-workflow-run', []),
 ('/actions/runs/{run_id}', 'delete', 'actions/delete-workflow-run', 'Delete a workflow run', 'rest/reference/actions#delete-a-workflow-run', []),
 ('/actions/runs/{run_id}/artifacts', 'get', 'actions/list-workflow-run-artifacts', 'List workflow run artifacts', 'rest/reference/actions#list-workflow-run-artifacts', []),
 ('/actions/runs/{run_id}/cancel', 'post', 'actions/cancel-workflow-run', 'Cancel a workflow run', 'rest/reference/actions#cancel-a-workflow-run', []),
 ('/actions/runs/{run_id}/jobs', 'get', 'actions/list-jobs-for-workflow-run', 'List jobs for a workflow run', 'rest/reference/actions#list-jobs-for-a-workflow-run', []),
 ('/actions/runs/{run_id}/logs', 'get', 'actions/download-workflow-run-logs', 'Download workflow run logs', 'rest/reference/actions#download-workflow-run-logs', []),
 ('/actions/runs/{run_id}/logs', 'delete', 'actions/delete-workflow-run-logs', 'Delete workflow run logs', 'rest/reference/actions#delete-workflow-run-logs', []),
 ('/actions/runs/{run_id}/rerun', 'post', 'actions/re-run-workflow', 'Re-run a workflow', 'rest/reference/actions#re-run-a-workflow', []),
 ('/actions/runs/{run_id}/timing', 'get', 'actions/get-workflow-run-usage', 'Get workflow run usage', 'rest/reference/actions#get-workflow-run-usage', []),
 ('/actions/secrets', 'get', 'actions/list-repo-secrets', 'List repository secrets', 'rest/reference/actions#list-repository-secrets', []),
 ('/actions/secrets/public-key', 'get', 'actions/get-repo-public-key', 'Get a repository public key', 'rest/reference/actions#get-a-repository-public-key', []),
 ('/actions/secrets/{secret_name}', 'get', 'actions/get-repo-secret', 'Get a repository secret', 'rest/reference/actions#get-a-repository-secret', []),
 ('/actions/secrets/{secret_name}', 'put', 'actions/create-or-update-repo-secret', 'Create or update a repository secret', 'rest/reference/actions#create-or-update-a-repository-secret', ['encrypted_value', 'key_id']),
 ('/actions/secrets/{secret_name}', 'delete', 'actions/delete-repo-secret', 'Delete a repository secret', 'rest/reference/actions#delete-a-repository-secret', []),
 ('/actions/workflows', 'get', 'actions/list-repo-workflows', 'List repository workflows', 'rest/reference/actions#list-repository-workflows', []),
 ('/actions/workflows/{workflow_id}', 'get', 'actions/get-workflow', 'Get a workflow', 'rest/reference/actions#get-a-workflow', []),
 ('/actions/workflows/{workflow_id}/disable', 'put', 'actions/disable-workflow', 'Disable a workflow', 'rest/reference/actions#disable-a-workflow', []),
 ('/actions/workflows/{workflow_id}/dispatches', 'post', 'actions/create-workflow-dispatch', 'Create a workflow dispatch event', 'rest/reference/actions#create-a-workflow-dispatch-event', ['ref', 'inputs']),
 ('/actions/workflows/{workflow_id}/enable', 'put', 'actions/enable-workflow', 'Enable a workflow', 'rest/reference/actions#enable-a-workflow', []),
 ('/actions/workflows/{workflow_id}/runs', 'get', 'actions/list-workflow-runs', 'List workflow runs', 'rest/reference/actions#list-workflow-runs', []),
 ('/actions/workflows/{workflow_id}/timing', 'get', 'actions/get-workflow-usage', 'Get workflow usage', 'rest/reference/actions#get-workflow-usage', []),
 ('/assignees', 'get', 'issues/list-assignees', 'List assignees', 'rest/reference/issues#list-assignees', []),
 ('/assignees/{assignee}', 'get', 'issues/check-user-can-be-assigned', 'Check if a user can be assigned', 'rest/reference/issues#check-if-a-user-can-be-assigned', []),
 ('/automated-security-fixes', 'put', 'repos/enable-automated-security-fixes', 'Enable automated security fixes', 'v3/repos/#enable-automated-security-fixes', []),
 ('/automated-security-fixes', 'delete', 'repos/disable-automated-security-fixes', 'Disable automated security fixes', 'v3/repos/#disable-automated-security-fixes', []),
 ('/branches', 'get', 'repos/list-branches', 'List branches', 'rest/reference/repos#list-branches', []),
 ('/branches/{branch}', 'get', 'repos/get-branch', 'Get a branch', 'rest/reference/repos#get-a-branch', []),
 ('/branches/{branch}/protection', 'get', 'repos/get-branch-protection', 'Get branch protection', 'rest/reference/repos#get-branch-protection', []),
 ('/branches/{branch}/protection', 'put', 'repos/update-branch-protection', 'Update branch protection', 'rest/reference/repos#update-branch-protection', ['required_status_checks', 'enforce_admins', 'required_pull_request_reviews', 'restrictions', 'required_linear_history', 'allow_force_pushes', 'allow_deletions']),
 ('/branches/{branch}/protection', 'delete', 'repos/delete-branch-protection', 'Delete branch protection', 'rest/reference/repos#delete-branch-protection', []),
 ('/branches/{branch}/protection/enforce_admins', 'get', 'repos/get-admin-branch-protection', 'Get admin branch protection', 'rest/reference/repos#get-admin-branch-protection', []),
 ('/branches/{branch}/protection/enforce_admins', 'post', 'repos/set-admin-branch-protection', 'Set admin branch protection', 'rest/reference/repos#set-admin-branch-protection', []),
 ('/branches/{branch}/protection/enforce_admins', 'delete', 'repos/delete-admin-branch-protection', 'Delete admin branch protection', 'rest/reference/repos#delete-admin-branch-protection', []),
 ('/branches/{branch}/protection/required_pull_request_reviews', 'get', 'repos/get-pull-request-review-protection', 'Get pull request review protection', 'rest/reference/repos#get-pull-request-review-protection', []),
 ('/branches/{branch}/protection/required_pull_request_reviews', 'patch', 'repos/update-pull-request-review-protection', 'Update pull request review protection', 'rest/reference/repos#update-pull-request-review-protection', ['dismissal_restrictions', 'dismiss_stale_reviews', 'require_code_owner_reviews', 'required_approving_review_count']),
 ('/branches/{branch}/protection/required_pull_request_reviews', 'delete', 'repos/delete-pull-request-review-protection', 'Delete pull request review protection', 'rest/reference/repos#delete-pull-request-review-protection', []),
 ('/branches/{branch}/protection/required_signatures', 'get', 'repos/get-commit-signature-protection', 'Get commit signature protection', 'rest/reference/repos#get-commit-signature-protection', []),
 ('/branches/{branch}/protection/required_signatures', 'post', 'repos/create-commit-signature-protection', 'Create commit signature protection', 'rest/reference/repos#create-commit-signature-protection', []),
 ('/branches/{branch}/protection/required_signatures', 'delete', 'repos/delete-commit-signature-protection', 'Delete commit signature protection', 'rest/reference/repos#delete-commit-signature-protection', []),
 ('/branches/{branch}/protection/required_status_checks', 'get', 'repos/get-status-checks-protection', 'Get status checks protection', 'rest/reference/repos#get-status-checks-protection', []),
 ('/branches/{branch}/protection/required_status_checks', 'patch', 'repos/update-status-check-protection', 'Update status check protection', 'rest/reference/repos#update-status-check-potection', ['strict', 'contexts']),
 ('/branches/{branch}/protection/required_status_checks', 'delete', 'repos/remove-status-check-protection', 'Remove status check protection', 'rest/reference/repos#remove-status-check-protection', []),
 ('/branches/{branch}/protection/required_status_checks/contexts', 'get', 'repos/get-all-status-check-contexts', 'Get all status check contexts', 'rest/reference/repos#get-all-status-check-contexts', []),
 ('/branches/{branch}/protection/required_status_checks/contexts', 'post', 'repos/add-status-check-contexts', 'Add status check contexts', 'rest/reference/repos#add-status-check-contexts', []),
 ('/branches/{branch}/protection/required_status_checks/contexts', 'put', 'repos/set-status-check-contexts', 'Set status check contexts', 'rest/reference/repos#set-status-check-contexts', []),
 ('/branches/{branch}/protection/required_status_checks/contexts', 'delete', 'repos/remove-status-check-contexts', 'Remove status check contexts', 'rest/reference/repos#remove-status-check-contexts', []),
 ('/branches/{branch}/protection/restrictions', 'get', 'repos/get-access-restrictions', 'Get access restrictions', 'rest/reference/repos#get-access-restrictions', []),
 ('/branches/{branch}/protection/restrictions', 'delete', 'repos/delete-access-restrictions', 'Delete access restrictions', 'rest/reference/repos#delete-access-restrictions', []),
 ('/branches/{branch}/protection/restrictions/apps', 'get', 'repos/get-apps-with-access-to-protected-branch', 'Get apps with access to the protected branch', 'rest/reference/repos#list-apps-with-access-to-the-protected-branch', []),
 ('/branches/{branch}/protection/restrictions/apps', 'post', 'repos/add-app-access-restrictions', 'Add app access restrictions', 'rest/reference/repos#add-app-access-restrictions', []),
 ('/branches/{branch}/protection/restrictions/apps', 'put', 'repos/set-app-access-restrictions', 'Set app access restrictions', 'rest/reference/repos#set-app-access-restrictions', []),
 ('/branches/{branch}/protection/restrictions/apps', 'delete', 'repos/remove-app-access-restrictions', 'Remove app access restrictions', 'rest/reference/repos#remove-app-access-restrictions', []),
 ('/branches/{branch}/protection/restrictions/teams', 'get', 'repos/get-teams-with-access-to-protected-branch', 'Get teams with access to the protected branch', 'rest/reference/repos#list-teams-with-access-to-the-protected-branch', []),
 ('/branches/{branch}/protection/restrictions/teams', 'post', 'repos/add-team-access-restrictions', 'Add team access restrictions', 'rest/reference/repos#add-team-access-restrictions', []),
 ('/branches/{branch}/protection/restrictions/teams', 'put', 'repos/set-team-access-restrictions', 'Set team access restrictions', 'rest/reference/repos#set-team-access-restrictions', []),
 ('/branches/{branch}/protection/restrictions/teams', 'delete', 'repos/remove-team-access-restrictions', 'Remove team access restrictions', 'rest/reference/repos#remove-team-access-restrictions', []),
 ('/branches/{branch}/protection/restrictions/users', 'get', 'repos/get-users-with-access-to-protected-branch', 'Get users with access to the protected branch', 'rest/reference/repos#list-users-with-access-to-the-protected-branch', []),
 ('/branches/{branch}/protection/restrictions/users', 'post', 'repos/add-user-access-restrictions', 'Add user access restrictions', 'rest/reference/repos#add-user-access-restrictions', []),
 ('/branches/{branch}/protection/restrictions/users', 'put', 'repos/set-user-access-restrictions', 'Set user access restrictions', 'rest/reference/repos#set-user-access-restrictions', []),
 ('/branches/{branch}/protection/restrictions/users', 'delete', 'repos/remove-user-access-restrictions', 'Remove user access restrictions', 'rest/reference/repos#remove-user-access-restrictions', []),
 ('/check-runs', 'post', 'checks/create', 'Create a check run', 'rest/reference/checks#create-a-check-run', ['name', 'head_sha', 'details_url', 'external_id', 'status', 'started_at', 'conclusion', 'completed_at', 'output', 'actions']),
 ('/check-runs/{check_run_id}', 'get', 'checks/get', 'Get a check run', 'rest/reference/checks#get-a-check-run', []),
 ('/check-runs/{check_run_id}', 'patch', 'checks/update', 'Update a check run', 'rest/reference/checks#update-a-check-run', ['name', 'details_url', 'external_id', 'started_at', 'status', 'conclusion', 'completed_at', 'output', 'actions']),
 ('/check-runs/{check_run_id}/annotations', 'get', 'checks/list-annotations', 'List check run annotations', 'rest/reference/checks#list-check-run-annotations', []),
 ('/check-suites', 'post', 'checks/create-suite', 'Create a check suite', 'rest/reference/checks#create-a-check-suite', ['head_sha']),
 ('/check-suites/preferences', 'patch', 'checks/set-suites-preferences', 'Update repository preferences for check suites', 'rest/reference/checks#update-repository-preferences-for-check-suites', ['auto_trigger_checks']),
 ('/check-suites/{check_suite_id}', 'get', 'checks/get-suite', 'Get a check suite', 'rest/reference/checks#get-a-check-suite', []),
 ('/check-suites/{check_suite_id}/check-runs', 'get', 'checks/list-for-suite', 'List check runs in a check suite', 'rest/reference/checks#list-check-runs-in-a-check-suite', []),
 ('/check-suites/{check_suite_id}/rerequest', 'post', 'checks/rerequest-suite', 'Rerequest a check suite', 'rest/reference/checks#rerequest-a-check-suite', []),
 ('/code-scanning/alerts', 'get', 'code-scanning/list-alerts-for-repo', 'List code scanning alerts for a repository', 'v3/code-scanning/#list-code-scanning-alerts-for-a-repository', []),
 ('/code-scanning/alerts/{alert_number}', 'get', 'code-scanning/get-alert', 'Get a code scanning alert', 'v3/code-scanning/#get-a-code-scanning-alert', []),
 ('/code-scanning/alerts/{alert_number}', 'patch', 'code-scanning/update-alert', 'Update a code scanning alert', 'v3/code-scanning/#upload-a-code-scanning-alert', ['state', 'dismissed_reason']),
 ('/code-scanning/analyses', 'get', 'code-scanning/list-recent-analyses', 'List recent code scanning analyses for a repository', 'v3/code-scanning/#list-recent-analyses', []),
 ('/code-scanning/sarifs', 'post', 'code-scanning/upload-sarif', 'Upload a SARIF file', 'v3/code-scanning/#upload-a-sarif-analysis', ['commit_sha', 'ref', 'sarif', 'checkout_uri', 'started_at', 'tool_name']),
 ('/collaborators', 'get', 'repos/list-collaborators', 'List repository collaborators', 'rest/reference/repos#list-repository-collaborators', []),
 ('/collaborators/{username}', 'get', 'repos/check-collaborator', 'Check if a user is a repository collaborator', 'rest/reference/repos#check-if-a-user-is-a-repository-collaborator', []),
 ('/collaborators/{username}', 'put', 'repos/add-collaborator', 'Add a repository collaborator', 'rest/reference/repos#add-a-repository-collaborator', ['permission', 'permissions']),
 ('/collaborators/{username}', 'delete', 'repos/remove-collaborator', 'Remove a repository collaborator', 'rest/reference/repos#remove-a-repository-collaborator', []),
 ('/collaborators/{username}/permission', 'get', 'repos/get-collaborator-permission-level', 'Get repository permissions for a user', 'rest/reference/repos#get-repository-permissions-for-a-user', []),
 ('/comments', 'get', 'repos/list-commit-comments-for-repo', 'List commit comments for a repository', 'rest/reference/repos#list-commit-comments-for-a-repository', []),
 ('/comments/{comment_id}', 'get', 'repos/get-commit-comment', 'Get a commit comment', 'rest/reference/repos#get-a-commit-comment', []),
 ('/comments/{comment_id}', 'patch', 'repos/update-commit-comment', 'Update a commit comment', 'rest/reference/repos#update-a-commit-comment', ['body']),
 ('/comments/{comment_id}', 'delete', 'repos/delete-commit-comment', 'Delete a commit comment', 'rest/reference/repos#delete-a-commit-comment', []),
 ('/comments/{comment_id}/reactions', 'get', 'reactions/list-for-commit-comment', 'List reactions for a commit comment', 'v3/reactions/#list-reactions-for-a-commit-comment', []),
 ('/comments/{comment_id}/reactions', 'post', 'reactions/create-for-commit-comment', 'Create reaction for a commit comment', 'v3/reactions/#create-reaction-for-a-commit-comment', ['content']),
 ('/comments/{comment_id}/reactions/{reaction_id}', 'delete', 'reactions/delete-for-commit-comment', 'Delete a commit comment reaction', 'v3/reactions/#delete-a-commit-comment-reaction', []),
 ('/commits', 'get', 'repos/list-commits', 'List commits', 'rest/reference/repos#list-commits', []),
 ('/commits/{commit_sha}/branches-where-head', 'get', 'repos/list-branches-for-head-commit', 'List branches for HEAD commit', 'rest/reference/repos#list-branches-for-head-commit', []),
 ('/commits/{commit_sha}/comments', 'get', 'repos/list-comments-for-commit', 'List commit comments', 'rest/reference/repos#list-commit-comments', []),
 ('/commits/{commit_sha}/comments', 'post', 'repos/create-commit-comment', 'Create a commit comment', 'rest/reference/repos#create-a-commit-comment', ['body', 'path', 'position', 'line']),
 ('/commits/{commit_sha}/pulls', 'get', 'repos/list-pull-requests-associated-with-commit', 'List pull requests associated with a commit', 'rest/reference/repos#list-pull-requests-associated-with-a-commit', []),
 ('/commits/{ref}', 'get', 'repos/get-commit', 'Get a commit', 'rest/reference/repos#get-a-commit', []),
 ('/commits/{ref}/check-runs', 'get', 'checks/list-for-ref', 'List check runs for a Git reference', 'rest/reference/checks#list-check-runs-for-a-git-reference', []),
 ('/commits/{ref}/check-suites', 'get', 'checks/list-suites-for-ref', 'List check suites for a Git reference', 'rest/reference/checks#list-check-suites-for-a-git-reference', []),
 ('/commits/{ref}/status', 'get', 'repos/get-combined-status-for-ref', 'Get the combined status for a specific reference', 'rest/reference/repos#get-the-combined-status-for-a-specific-reference', []),
 ('/commits/{ref}/statuses', 'get', 'repos/list-commit-statuses-for-ref', 'List commit statuses for a reference', 'rest/reference/repos#list-commit-statuses-for-a-reference', []),
 ('/community/code_of_conduct', 'get', 'codes-of-conduct/get-for-repo', 'Get the code of conduct for a repository', 'v3/codes_of_conduct/#get-the-code-of-conduct-for-a-repository', []),
 ('/community/profile', 'get', 'repos/get-community-profile-metrics', 'Get community profile metrics', 'rest/reference/repos#get-community-profile-metrics', []),
 ('/compare/{base}...{head}', 'get', 'repos/compare-commits', 'Compare two commits', 'rest/reference/repos#compare-two-commits', []),
 ('/contents/{path}', 'get', 'repos/get-content', 'Get repository content', 'rest/reference/repos#get-repository-content', []),
 ('/contents/{path}', 'put', 'repos/create-or-update-file-contents', 'Create or update file contents', 'rest/reference/repos#create-or-update-file-contents', ['message', 'content', 'sha', 'branch', 'committer', 'author']),
 ('/contents/{path}', 'delete', 'repos/delete-file', 'Delete a file', 'rest/reference/repos#delete-a-file', ['message', 'sha', 'branch', 'committer', 'author']),
 ('/contributors', 'get', 'repos/list-contributors', 'List repository contributors', 'v3/repos/#list-repository-contributors', []),
 ('/deployments', 'get', 'repos/list-deployments', 'List deployments', 'rest/reference/repos#list-deployments', []),
 ('/deployments', 'post', 'repos/create-deployment', 'Create a deployment', 'rest/reference/repos#create-a-deployment', ['ref', 'task', 'auto_merge', 'required_contexts', 'payload', 'environment', 'description', 'transient_environment', 'production_environment', 'created_at']),
 ('/deployments/{deployment_id}', 'get', 'repos/get-deployment', 'Get a deployment', 'rest/reference/repos#get-a-deployment', []),
 ('/deployments/{deployment_id}', 'delete', 'repos/delete-deployment', 'Delete a deployment', 'rest/reference/repos#delete-a-deployment', []),
 ('/deployments/{deployment_id}/statuses', 'get', 'repos/list-deployment-statuses', 'List deployment statuses', 'rest/reference/repos#list-deployment-statuses', []),
 ('/deployments/{deployment_id}/statuses', 'post', 'repos/create-deployment-status', 'Create a deployment status', 'rest/reference/repos#create-a-deployment-status', ['state', 'target_url', 'log_url', 'description', 'environment', 'environment_url', 'auto_inactive']),
 ('/deployments/{deployment_id}/statuses/{status_id}', 'get', 'repos/get-deployment-status', 'Get a deployment status', 'rest/reference/repos#get-a-deployment-status', []),
 ('/dispatches', 'post', 'repos/create-dispatch-event', 'Create a repository dispatch event', 'v3/repos/#create-a-repository-dispatch-event', ['event_type', 'client_payload']),
 ('/events', 'get', 'activity/list-repo-events', 'List repository events', 'rest/reference/activity#list-repository-events', []),
 ('/forks', 'get', 'repos/list-forks', 'List forks', 'rest/reference/repos#list-forks', []),
 ('/forks', 'post', 'repos/create-fork', 'Create a fork', 'rest/reference/repos#create-a-fork', ['organization']),
 ('/git/blobs', 'post', 'git/create-blob', 'Create a blob', 'rest/reference/git#create-a-blob', ['content', 'encoding']),
 ('/git/blobs/{file_sha}', 'get', 'git/get-blob', 'Get a blob', 'rest/reference/git#get-a-blob', []),
 ('/git/commits', 'post', 'git/create-commit', 'Create a commit', 'rest/reference/git#create-a-commit', ['message', 'tree', 'parents', 'author', 'committer', 'signature']),
 ('/git/commits/{commit_sha}', 'get', 'git/get-commit', 'Get a commit', 'rest/reference/git#get-a-commit', []),
 ('/git/matching-refs/{ref}', 'get', 'git/list-matching-refs', 'List matching references', 'rest/reference/git#list-matching-references', []),
 ('/git/ref/{ref}', 'get', 'git/get-ref', 'Get a reference', 'rest/reference/git#get-a-reference', []),
 ('/git/refs', 'post', 'git/create-ref', 'Create a reference', 'rest/reference/git#create-a-reference', ['ref', 'sha', 'key']),
 ('/git/refs/{ref}', 'patch', 'git/update-ref', 'Update a reference', 'rest/reference/git#update-a-reference', ['sha', 'force']),
 ('/git/refs/{ref}', 'delete', 'git/delete-ref', 'Delete a reference', 'rest/reference/git#delete-a-reference', []),
 ('/git/tags', 'post', 'git/create-tag', 'Create a tag object', 'rest/reference/git#create-a-tag-object', ['tag', 'message', 'object', 'type', 'tagger']),
 ('/git/tags/{tag_sha}', 'get', 'git/get-tag', 'Get a tag', 'rest/reference/git#get-a-tag', []),
 ('/git/trees', 'post', 'git/create-tree', 'Create a tree', 'rest/reference/git#create-a-tree', ['tree', 'base_tree']),
 ('/git/trees/{tree_sha}', 'get', 'git/get-tree', 'Get a tree', 'rest/reference/git#get-a-tree', []),
 ('/hooks', 'get', 'repos/list-webhooks', 'List repository webhooks', 'rest/reference/repos#list-repository-webhooks', []),
 ('/hooks', 'post', 'repos/create-webhook', 'Create a repository webhook', 'rest/reference/repos#create-a-repository-webhook', ['name', 'config', 'events', 'active']),
 ('/hooks/{hook_id}', 'get', 'repos/get-webhook', 'Get a repository webhook', 'rest/reference/repos#get-a-repository-webhook', []),
 ('/hooks/{hook_id}', 'patch', 'repos/update-webhook', 'Update a repository webhook', 'rest/reference/repos#update-a-repository-webhook', ['config', 'events', 'add_events', 'remove_events', 'active']),
 ('/hooks/{hook_id}', 'delete', 'repos/delete-webhook', 'Delete a repository webhook', 'rest/reference/repos#delete-a-repository-webhook', []),
 ('/hooks/{hook_id}/config', 'get', 'repos/get-webhook-config-for-repo', 'Get a webhook configuration for a repository', 'v3/repos#get-a-webhook-configuration-for-a-repository', []),
 ('/hooks/{hook_id}/config', 'patch', 'repos/update-webhook-config-for-repo', 'Update a webhook configuration for a repository', 'v3/repos#update-a-webhook-configuration-for-a-repository', ['url', 'content_type', 'secret', 'insecure_ssl']),
 ('/hooks/{hook_id}/pings', 'post', 'repos/ping-webhook', 'Ping a repository webhook', 'rest/reference/repos#ping-a-repository-webhook', []),
 ('/hooks/{hook_id}/tests', 'post', 'repos/test-push-webhook', 'Test the push repository webhook', 'rest/reference/repos#test-the-push-repository-webhook', []),
 ('/import', 'get', 'migrations/get-import-status', 'Get an import status', 'rest/reference/migrations#get-an-import-status', []),
 ('/import', 'put', 'migrations/start-import', 'Start an import', 'rest/reference/migrations#start-an-import', ['vcs_url', 'vcs', 'vcs_username', 'vcs_password', 'tfvc_project']),
 ('/import', 'patch', 'migrations/update-import', 'Update an import', 'rest/reference/migrations#update-an-import', ['vcs_username', 'vcs_password', 'vcs', 'tfvc_project']),
 ('/import', 'delete', 'migrations/cancel-import', 'Cancel an import', 'rest/reference/migrations#cancel-an-import', []),
 ('/import/authors', 'get', 'migrations/get-commit-authors', 'Get commit authors', 'rest/reference/migrations#get-commit-authors', []),
 ('/import/authors/{author_id}', 'patch', 'migrations/map-commit-author', 'Map a commit author', 'rest/reference/migrations#map-a-commit-author', ['email', 'name', 'remote_id']),
 ('/import/large_files', 'get', 'migrations/get-large-files', 'Get large files', 'rest/reference/migrations#get-large-files', []),
 ('/import/lfs', 'patch', 'migrations/set-lfs-preference', 'Update Git LFS preference', 'rest/reference/migrations#update-git-lfs-preference', ['use_lfs']),
 ('/installation', 'get', 'apps/get-repo-installation', 'Get a repository installation for the authenticated app', 'v3/apps/#get-a-repository-installation-for-the-authenticated-app', []),
 ('/interaction-limits', 'get', 'interactions/get-restrictions-for-repo', 'Get interaction restrictions for a repository', 'rest/reference/interactions#get-interaction-restrictions-for-a-repository', []),
 ('/interaction-limits', 'put', 'interactions/set-restrictions-for-repo', 'Set interaction restrictions for a repository', 'rest/reference/interactions#set-interaction-restrictions-for-a-repository', ['limit']),
 ('/interaction-limits', 'delete', 'interactions/remove-restrictions-for-repo', 'Remove interaction restrictions for a repository', 'rest/reference/interactions#remove-interaction-restrictions-for-a-repository', []),
 ('/invitations', 'get', 'repos/list-invitations', 'List repository invitations', 'rest/reference/repos#list-repository-invitations', []),
 ('/invitations/{invitation_id}', 'patch', 'repos/update-invitation', 'Update a repository invitation', 'rest/reference/repos#update-a-repository-invitation', ['permissions']),
 ('/invitations/{invitation_id}', 'delete', 'repos/delete-invitation', 'Delete a repository invitation', 'rest/reference/repos#delete-a-repository-invitation', []),
 ('/issues', 'get', 'issues/list-for-repo', 'List repository issues', 'v3/issues/#list-repository-issues', []),
 ('/issues', 'post', 'issues/create', 'Create an issue', 'v3/issues/#create-an-issue', ['title', 'body', 'assignee', 'milestone', 'labels', 'assignees']),
 ('/issues/comments', 'get', 'issues/list-comments-for-repo', 'List issue comments for a repository', 'rest/reference/issues#list-issue-comments-for-a-repository', []),
 ('/issues/comments/{comment_id}', 'get', 'issues/get-comment', 'Get an issue comment', 'rest/reference/issues#get-an-issue-comment', []),
 ('/issues/comments/{comment_id}', 'patch', 'issues/update-comment', 'Update an issue comment', 'rest/reference/issues#update-an-issue-comment', ['body']),
 ('/issues/comments/{comment_id}', 'delete', 'issues/delete-comment', 'Delete an issue comment', 'rest/reference/issues#delete-an-issue-comment', []),
 ('/issues/comments/{comment_id}/reactions', 'get', 'reactions/list-for-issue-comment', 'List reactions for an issue comment', 'v3/reactions/#list-reactions-for-an-issue-comment', []),
 ('/issues/comments/{comment_id}/reactions', 'post', 'reactions/create-for-issue-comment', 'Create reaction for an issue comment', 'v3/reactions/#create-reaction-for-an-issue-comment', ['content']),
 ('/issues/comments/{comment_id}/reactions/{reaction_id}', 'delete', 'reactions/delete-for-issue-comment', 'Delete an issue comment reaction', 'v3/reactions/#delete-an-issue-comment-reaction', []),
 ('/issues/events', 'get', 'issues/list-events-for-repo', 'List issue events for a repository', 'rest/reference/issues#list-issue-events-for-a-repository', []),
 ('/issues/events/{event_id}', 'get', 'issues/get-event', 'Get an issue event', 'rest/reference/issues#get-an-issue-event', []),
 ('/issues/{issue_number}', 'get', 'issues/get', 'Get an issue', 'v3/issues/#get-an-issue', []),
 ('/issues/{issue_number}', 'patch', 'issues/update', 'Update an issue', 'v3/issues/#update-an-issue', ['title', 'body', 'assignee', 'state', 'milestone', 'labels', 'assignees']),
 ('/issues/{issue_number}/assignees', 'post', 'issues/add-assignees', 'Add assignees to an issue', 'rest/reference/issues#add-assignees-to-an-issue', ['assignees']),
 ('/issues/{issue_number}/assignees', 'delete', 'issues/remove-assignees', 'Remove assignees from an issue', 'rest/reference/issues#remove-assignees-from-an-issue', ['assignees']),
 ('/issues/{issue_number}/comments', 'get', 'issues/list-comments', 'List issue comments', 'rest/reference/issues#list-issue-comments', []),
 ('/issues/{issue_number}/comments', 'post', 'issues/create-comment', 'Create an issue comment', 'rest/reference/issues#create-an-issue-comment', ['body']),
 ('/issues/{issue_number}/events', 'get', 'issues/list-events', 'List issue events', 'rest/reference/issues#list-issue-events', []),
 ('/issues/{issue_number}/labels', 'get', 'issues/list-labels-on-issue', 'List labels for an issue', 'rest/reference/issues#list-labels-for-an-issue', []),
 ('/issues/{issue_number}/labels', 'post', 'issues/add-labels', 'Add labels to an issue', 'rest/reference/issues#add-labels-to-an-issue', ['labels']),
 ('/issues/{issue_number}/labels', 'put', 'issues/set-labels', 'Set labels for an issue', 'rest/reference/issues#set-labels-for-an-issue', ['labels']),
 ('/issues/{issue_number}/labels', 'delete', 'issues/remove-all-labels', 'Remove all labels from an issue', 'rest/reference/issues#remove-all-labels-from-an-issue', []),
 ('/issues/{issue_number}/labels/{name}', 'delete', 'issues/remove-label', 'Remove a label from an issue', 'rest/reference/issues#remove-a-label-from-an-issue', []),
 ('/issues/{issue_number}/lock', 'put', 'issues/lock', 'Lock an issue', 'v3/issues/#lock-an-issue', ['lock_reason']),
 ('/issues/{issue_number}/lock', 'delete', 'issues/unlock', 'Unlock an issue', 'v3/issues/#unlock-an-issue', []),
 ('/issues/{issue_number}/reactions', 'get', 'reactions/list-for-issue', 'List reactions for an issue', 'v3/reactions/#list-reactions-for-an-issue', []),
 ('/issues/{issue_number}/reactions', 'post', 'reactions/create-for-issue', 'Create reaction for an issue', 'v3/reactions/#create-reaction-for-an-issue', ['content']),
 ('/issues/{issue_number}/reactions/{reaction_id}', 'delete', 'reactions/delete-for-issue', 'Delete an issue reaction', 'v3/reactions/#delete-an-issue-reaction', []),
 ('/issues/{issue_number}/timeline', 'get', 'issues/list-events-for-timeline', 'List timeline events for an issue', 'rest/reference/issues#list-timeline-events-for-an-issue', []),
 ('/keys', 'get', 'repos/list-deploy-keys', 'List deploy keys', 'rest/reference/repos#list-deploy-keys', []),
 ('/keys', 'post', 'repos/create-deploy-key', 'Create a deploy key', 'rest/reference/repos#create-a-deploy-key', ['title', 'key', 'read_only']),
 ('/keys/{key_id}', 'get', 'repos/get-deploy-key', 'Get a deploy key', 'rest/reference/repos#get-a-deploy-key', []),
 ('/keys/{key_id}', 'delete', 'repos/delete-deploy-key', 'Delete a deploy key', 'rest/reference/repos#delete-a-deploy-key', []),
 ('/labels', 'get', 'issues/list-labels-for-repo', 'List labels for a repository', 'rest/reference/issues#list-labels-for-a-repository', []),
 ('/labels', 'post', 'issues/create-label', 'Create a label', 'rest/reference/issues#create-a-label', ['name', 'color', 'description']),
 ('/labels/{name}', 'get', 'issues/get-label', 'Get a label', 'rest/reference/issues#get-a-label', []),
 ('/labels/{name}', 'patch', 'issues/update-label', 'Update a label', 'rest/reference/issues#update-a-label', ['new_name', 'color', 'description']),
 ('/labels/{name}', 'delete', 'issues/delete-label', 'Delete a label', 'rest/reference/issues#delete-a-label', []),
 ('/languages', 'get', 'repos/list-languages', 'List repository languages', 'v3/repos/#list-repository-languages', []),
 ('/license', 'get', 'licenses/get-for-repo', 'Get the license for a repository', 'v3/licenses/#get-the-license-for-a-repository', []),
 ('/merges', 'post', 'repos/merge', 'Merge a branch', 'rest/reference/repos#merge-a-branch', ['base', 'head', 'commit_message']),
 ('/milestones', 'get', 'issues/list-milestones', 'List milestones', 'rest/reference/issues#list-milestones', []),
 ('/milestones', 'post', 'issues/create-milestone', 'Create a milestone', 'rest/reference/issues#create-a-milestone', ['title', 'state', 'description', 'due_on']),
 ('/milestones/{milestone_number}', 'get', 'issues/get-milestone', 'Get a milestone', 'rest/reference/issues#get-a-milestone', []),
 ('/milestones/{milestone_number}', 'patch', 'issues/update-milestone', 'Update a milestone', 'rest/reference/issues#update-a-milestone', ['title', 'state', 'description', 'due_on']),
 ('/milestones/{milestone_number}', 'delete', 'issues/delete-milestone', 'Delete a milestone', 'rest/reference/issues#delete-a-milestone', []),
 ('/milestones/{milestone_number}/labels', 'get', 'issues/list-labels-for-milestone', 'List labels for issues in a milestone', 'rest/reference/issues#list-labels-for-issues-in-a-milestone', []),
 ('/notifications', 'get', 'activity/list-repo-notifications-for-authenticated-user', 'List repository notifications for the authenticated user', 'rest/reference/activity#list-repository-notifications-for-the-authenticated-user', []),
 ('/notifications', 'put', 'activity/mark-repo-notifications-as-read', 'Mark repository notifications as read', 'rest/reference/activity#mark-repository-notifications-as-read', ['last_read_at']),
 ('/pages', 'get', 'repos/get-pages', 'Get a GitHub Pages site', 'rest/reference/repos#get-a-github-pages-site', []),
 ('/pages', 'post', 'repos/create-pages-site', 'Create a GitHub Pages site', 'rest/reference/repos#create-a-github-pages-site', ['source']),
 ('/pages', 'put', 'repos/update-information-about-pages-site', 'Update information about a GitHub Pages site', 'rest/reference/repos#update-information-about-a-github-pages-site', ['cname', 'source']),
 ('/pages', 'delete', 'repos/delete-pages-site', 'Delete a GitHub Pages site', 'rest/reference/repos#delete-a-github-pages-site', []),
 ('/pages/builds', 'get', 'repos/list-pages-builds', 'List GitHub Pages builds', 'rest/reference/repos#list-github-pages-builds', []),
 ('/pages/builds', 'post', 'repos/request-pages-build', 'Request a GitHub Pages build', 'rest/reference/repos#request-a-github-pages-build', []),
 ('/pages/builds/latest', 'get', 'repos/get-latest-pages-build', 'Get latest Pages build', 'rest/reference/repos#get-latest-pages-build', []),
 ('/pages/builds/{build_id}', 'get', 'repos/get-pages-build', 'Get GitHub Pages build', 'rest/reference/repos#get-github-pages-build', []),
 ('/projects', 'get', 'projects/list-for-repo', 'List repository projects', 'v3/projects/#list-repository-projects', []),
 ('/projects', 'post', 'projects/create-for-repo', 'Create a repository project', 'v3/projects/#create-a-repository-project', ['name', 'body']),
 ('/pulls', 'get', 'pulls/list', 'List pull requests', 'v3/pulls/#list-pull-requests', []),
 ('/pulls', 'post', 'pulls/create', 'Create a pull request', 'v3/pulls/#create-a-pull-request', ['title', 'head', 'base', 'body', 'maintainer_can_modify', 'draft', 'issue']),
 ('/pulls/comments', 'get', 'pulls/list-review-comments-for-repo', 'List review comments in a repository', 'rest/reference/pulls#list-review-comments-in-a-repository', []),
 ('/pulls/comments/{comment_id}', 'get', 'pulls/get-review-comment', 'Get a review comment for a pull request', 'rest/reference/pulls#get-a-review-comment-for-a-pull-request', []),
 ('/pulls/comments/{comment_id}', 'patch', 'pulls/update-review-comment', 'Update a review comment for a pull request', 'rest/reference/pulls#update-a-review-comment-for-a-pull-request', ['body']),
 ('/pulls/comments/{comment_id}', 'delete', 'pulls/delete-review-comment', 'Delete a review comment for a pull request', 'rest/reference/pulls#delete-a-review-comment-for-a-pull-request', []),
 ('/pulls/comments/{comment_id}/reactions', 'get', 'reactions/list-for-pull-request-review-comment', 'List reactions for a pull request review comment', 'v3/reactions/#list-reactions-for-a-pull-request-review-comment', []),
 ('/pulls/comments/{comment_id}/reactions', 'post', 'reactions/create-for-pull-request-review-comment', 'Create reaction for a pull request review comment', 'v3/reactions/#create-reaction-for-a-pull-request-review-comment', ['content']),
 ('/pulls/comments/{comment_id}/reactions/{reaction_id}', 'delete', 'reactions/delete-for-pull-request-comment', 'Delete a pull request comment reaction', 'v3/reactions/#delete-a-pull-request-comment-reaction', []),
 ('/pulls/{pull_number}', 'get', 'pulls/get', 'Get a pull request', 'v3/pulls/#get-a-pull-request', []),
 ('/pulls/{pull_number}', 'patch', 'pulls/update', 'Update a pull request', 'v3/pulls/#update-a-pull-request', ['title', 'body', 'state', 'base', 'maintainer_can_modify']),
 ('/pulls/{pull_number}/comments', 'get', 'pulls/list-review-comments', 'List review comments on a pull request', 'rest/reference/pulls#list-review-comments-on-a-pull-request', []),
 ('/pulls/{pull_number}/comments', 'post', 'pulls/create-review-comment', 'Create a review comment for a pull request', 'rest/reference/pulls#create-a-review-comment-for-a-pull-request', ['body', 'commit_id', 'path', 'position', 'side', 'line', 'start_line', 'start_side', 'in_reply_to']),
 ('/pulls/{pull_number}/comments/{comment_id}/replies', 'post', 'pulls/create-reply-for-review-comment', 'Create a reply for a review comment', 'rest/reference/pulls#create-a-reply-for-a-review-comment', ['body']),
 ('/pulls/{pull_number}/commits', 'get', 'pulls/list-commits', 'List commits on a pull request', 'v3/pulls/#list-commits-on-a-pull-request', []),
 ('/pulls/{pull_number}/files', 'get', 'pulls/list-files', 'List pull requests files', 'v3/pulls/#list-pull-requests-files', []),
 ('/pulls/{pull_number}/merge', 'get', 'pulls/check-if-merged', 'Check if a pull request has been merged', 'v3/pulls/#check-if-a-pull-request-has-been-merged', []),
 ('/pulls/{pull_number}/merge', 'put', 'pulls/merge', 'Merge a pull request', 'v3/pulls/#merge-a-pull-request', ['commit_title', 'commit_message', 'sha', 'merge_method']),
 ('/pulls/{pull_number}/requested_reviewers', 'get', 'pulls/list-requested-reviewers', 'List requested reviewers for a pull request', 'rest/reference/pulls#list-requested-reviewers-for-a-pull-request', []),
 ('/pulls/{pull_number}/requested_reviewers', 'post', 'pulls/request-reviewers', 'Request reviewers for a pull request', 'rest/reference/pulls#request-reviewers-for-a-pull-request', ['reviewers', 'team_reviewers']),
 ('/pulls/{pull_number}/requested_reviewers', 'delete', 'pulls/remove-requested-reviewers', 'Remove requested reviewers from a pull request', 'rest/reference/pulls#remove-requested-reviewers-from-a-pull-request', ['reviewers', 'team_reviewers']),
 ('/pulls/{pull_number}/reviews', 'get', 'pulls/list-reviews', 'List reviews for a pull request', 'rest/reference/pulls#list-reviews-for-a-pull-request', []),
 ('/pulls/{pull_number}/reviews', 'post', 'pulls/create-review', 'Create a review for a pull request', 'rest/reference/pulls#create-a-review-for-a-pull-request', ['commit_id', 'body', 'event', 'comments']),
 ('/pulls/{pull_number}/reviews/{review_id}', 'get', 'pulls/get-review', 'Get a review for a pull request', 'rest/reference/pulls#get-a-review-for-a-pull-request', []),
 ('/pulls/{pull_number}/reviews/{review_id}', 'put', 'pulls/update-review', 'Update a review for a pull request', 'rest/reference/pulls#update-a-review-for-a-pull-request', ['body']),
 ('/pulls/{pull_number}/reviews/{review_id}', 'delete', 'pulls/delete-pending-review', 'Delete a pending review for a pull request', 'rest/reference/pulls#delete-a-pending-review-for-a-pull-request', []),
 ('/pulls/{pull_number}/reviews/{review_id}/comments', 'get', 'pulls/list-comments-for-review', 'List comments for a pull request review', 'rest/reference/pulls#list-comments-for-a-pull-request-review', []),
 ('/pulls/{pull_number}/reviews/{review_id}/dismissals', 'put', 'pulls/dismiss-review', 'Dismiss a review for a pull request', 'rest/reference/pulls#dismiss-a-review-for-a-pull-request', ['message', 'event']),
 ('/pulls/{pull_number}/reviews/{review_id}/events', 'post', 'pulls/submit-review', 'Submit a review for a pull request', 'rest/reference/pulls#submit-a-review-for-a-pull-request', ['body', 'event']),
 ('/pulls/{pull_number}/update-branch', 'put', 'pulls/update-branch', 'Update a pull request branch', 'v3/pulls/#update-a-pull-request-branch', ['expected_head_sha']),
 ('/readme', 'get', 'repos/get-readme', 'Get a repository README', 'rest/reference/repos#get-a-repository-readme', []),
 ('/releases', 'get', 'repos/list-releases', 'List releases', 'rest/reference/repos#list-releases', []),
 ('/releases', 'post', 'repos/create-release', 'Create a release', 'rest/reference/repos#create-a-release', ['tag_name', 'target_commitish', 'name', 'body', 'draft', 'prerelease']),
 ('/releases/assets/{asset_id}', 'get', 'repos/get-release-asset', 'Get a release asset', 'rest/reference/repos#get-a-release-asset', []),
 ('/releases/assets/{asset_id}', 'patch', 'repos/update-release-asset', 'Update a release asset', 'rest/reference/repos#update-a-release-asset', ['name', 'label', 'state']),
 ('/releases/assets/{asset_id}', 'delete', 'repos/delete-release-asset', 'Delete a release asset', 'rest/reference/repos#delete-a-release-asset', []),
 ('/releases/latest', 'get', 'repos/get-latest-release', 'Get the latest release', 'rest/reference/repos#get-the-latest-release', []),
 ('/releases/tags/{tag}', 'get', 'repos/get-release-by-tag', 'Get a release by tag name', 'rest/reference/repos#get-a-release-by-tag-name', []),
 ('/releases/{release_id}', 'get', 'repos/get-release', 'Get a release', 'rest/reference/repos#get-a-release', []),
 ('/releases/{release_id}', 'patch', 'repos/update-release', 'Update a release', 'rest/reference/repos#update-a-release', ['tag_name', 'target_commitish', 'name', 'body', 'draft', 'prerelease']),
 ('/releases/{release_id}', 'delete', 'repos/delete-release', 'Delete a release', 'rest/reference/repos#delete-a-release', []),
 ('/releases/{release_id}/assets', 'get', 'repos/list-release-assets', 'List release assets', 'rest/reference/repos#list-release-assets', []),
 ('/releases/{release_id}/assets', 'post', 'repos/upload-release-asset', 'Upload a release asset', 'rest/reference/repos#upload-a-release-asset', []),
 ('/stargazers', 'get', 'activity/list-stargazers-for-repo', 'List stargazers', 'rest/reference/activity#list-stargazers', []),
 ('/stats/code_frequency', 'get', 'repos/get-code-frequency-stats', 'Get the weekly commit activity', 'rest/reference/repos#get-the-weekly-commit-activity', []),
 ('/stats/commit_activity', 'get', 'repos/get-commit-activity-stats', 'Get the last year of commit activity', 'rest/reference/repos#get-the-last-year-of-commit-activity', []),
 ('/stats/contributors', 'get', 'repos/get-contributors-stats', 'Get all contributor commit activity', 'rest/reference/repos#get-all-contributor-commit-activity', []),
 ('/stats/participation', 'get', 'repos/get-participation-stats', 'Get the weekly commit count', 'rest/reference/repos#get-the-weekly-commit-count', []),
 ('/stats/punch_card', 'get', 'repos/get-punch-card-stats', 'Get the hourly commit count for each day', 'rest/reference/repos#get-the-hourly-commit-count-for-each-day', []),
 ('/statuses/{sha}', 'post', 'repos/create-commit-status', 'Create a commit status', 'rest/reference/repos#create-a-commit-status', ['state', 'target_url', 'description', 'context']),
 ('/subscribers', 'get', 'activity/list-watchers-for-repo', 'List watchers', 'rest/reference/activity#list-watchers', []),
 ('/subscription', 'get', 'activity/get-repo-subscription', 'Get a repository subscription', 'rest/reference/activity#get-a-repository-subscription', []),
 ('/subscription', 'put', 'activity/set-repo-subscription', 'Set a repository subscription', 'rest/reference/activity#set-a-repository-subscription', ['subscribed', 'ignored']),
 ('/subscription', 'delete', 'activity/delete-repo-subscription', 'Delete a repository subscription', 'rest/reference/activity#delete-a-repository-subscription', []),
 ('/tags', 'get', 'repos/list-tags', 'List repository tags', 'v3/repos/#list-repository-tags', []),
 ('/tarball/{ref}', 'get', 'repos/download-tarball-archive', 'Download a repository archive (tar)', 'rest/reference/repos#download-a-repository-archive', []),
 ('/teams', 'get', 'repos/list-teams', 'List repository teams', 'v3/repos/#list-repository-teams', []),
 ('/topics', 'get', 'repos/get-all-topics', 'Get all repository topics', 'v3/repos/#get-all-repository-topics', []),
 ('/topics', 'put', 'repos/replace-all-topics', 'Replace all repository topics', 'v3/repos/#replace-all-repository-topics', ['names']),
 ('/traffic/clones', 'get', 'repos/get-clones', 'Get repository clones', 'rest/reference/repos#get-repository-clones', []),
 ('/traffic/popular/paths', 'get', 'repos/get-top-paths', 'Get top referral paths', 'rest/reference/repos#get-top-referral-paths', []),
 ('/traffic/popular/referrers', 'get', 'repos/get-top-referrers', 'Get top referral sources', 'rest/reference/repos#get-top-referral-sources', []),
 ('/traffic/views', 'get', 'repos/get-views', 'Get page views', 'rest/reference/repos#get-page-views', []),
 ('/transfer', 'post', 'repos/transfer', 'Transfer a repository', 'v3/repos/#transfer-a-repository', ['new_owner', 'team_ids']),
 ('/vulnerability-alerts', 'get', 'repos/check-vulnerability-alerts', 'Check if vulnerability alerts are enabled for a repository', 'v3/repos/#check-if-vulnerability-alerts-are-enabled-for-a-repository', []),
 ('/vulnerability-alerts', 'put', 'repos/enable-vulnerability-alerts', 'Enable vulnerability alerts', 'v3/repos/#enable-vulnerability-alerts', []),
 ('/vulnerability-alerts', 'delete', 'repos/disable-vulnerability-alerts', 'Disable vulnerability alerts', 'v3/repos/#disable-vulnerability-alerts', []),
 ('/zipball/{ref}', 'get', 'repos/download-zipball-archive', 'Download a repository archive (zip)', 'rest/reference/repos#download-a-repository-archive', [])]