source "https://rubygems.org"

#gem "nokogiri", "< 1.10.9"
gem "jekyll", ">= 3.7"
gem "jekyll-remote-theme"
#gem "kramdown", ">= 2.3.0"
#gem "jekyll-octicons"
#gem "jekyll-gist"
#gem "jekyll-paginate"
#gem "kramdown-math-katex"

